export interface ParcelProperties {
  object_id: number;
  state: string;
  state_enabling_act: string | null;
  trust_name: string;
  managing_agency: string;
  university: string;
  acres: number | null;
  gis_acres: number | null;
  net_acres: null;
  rights_type: 'surface' | 'subsurface' | 'timber';
  activity: string | null;
  reported_county: string | null;
  census_bureau_reported_county: string | null;
  meridian: string | null;
  township: string | null;
  range: string | null;
  section: string | null;
  aliquot: string | null;
  block: string | null;
  data_source: string | null;
  parcel_count: number | null;
  all_cession_numbers: string | null;
  price_paid_for_parcel: number | null;
  cession_num_01: string | null;
  C1_price_paid_per_acre: string | null;
  C1_present_day_tribe: string | null;
  'C1_tribe_named_in_land_cessions_1784-1894': string | null;
  cession_num_02: string | null;
  C2_price_paid_per_acre: string | null;
  C2_present_day_tribe: string | null;
  'C2_tribe_named_in_land_cessions_1784-1894': string | null;
  cession_num_03: string | null;
  C3_present_day_tribe: string | null;
  'C3_tribe_named_in_land_cessions_1784-1894': string | null;
  cession_num_04: string | null;
  C3_price_paid_per_acre: string | null;
  C4_present_day_tribe: string | null;
  'C4_tribe_named_in_land_cessions_1784-1894': string | null;
  cession_num_05: string | null;
  C4_price_paid_per_acre: string | null;
  C5_present_day_tribe: string | null;
  'C5_tribe_named_in_land_cessions_1784-1894': string | null;
  cession_num_06: string | null;
  C5_price_paid_per_acre: string | null;
  C6_present_day_tribe: string | null;
  'C6_tribe_named_in_land_cessions_1784-1894': string | null;
  cession_num_07: string | null;
  C6_price_paid_per_acre: string | null;
  C7_present_day_tribe: string | null;
  'C7_tribe_named_in_land_cessions_1784-1894': string | null;
  cession_num_08: string | null;
  C7_price_paid_per_acre: string | null;
  C8_present_day_tribe: string | null;
  'C8_tribe_named_in_land_cessions_1784-1894': string | null;
}
